services:
  server:
    image: azerty78/ben-djibril-site:latest
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:4001:80"
    restart: unless-stopped
    container_name: ben-djibril-site
